### PR TITLE
Fetch welcome message from a remote wiki page

### PR DESCRIPTION
**Pull request by samuelguebo**
Fix issue #3 suggested by @Niharika29

### CODE REVIEW

**Comment by srish** [comment]
@samuelguebo It looks like the `fetch_welcome_message` as of now without the [links on this page](https://www.mediawiki.org/wiki/User:SSethi_(WMF)/Sandbox/Gerrit_newcomer_bot_text
) returns the text with <nowiki> tags in it and with links returns in wikitext format. Could you may be add a fix for it?

**Comment by samuelguebo** [comment]
@srish  Do you think that stripping tags would work?

**Comment by srish** [comment]
@samuelguebo Thanks! yes it works :) I am seeing some `Pylint` errors though, would you like to fix them? If not, I can also push a fix for it, after merging your changes!

**Comment by srish** [comment]
Also, [this declaration](https://github.com/srish/gerrit-newcomer-bot/pull/4/commits/9535158828e3cbdbfbb93e10295def84d5cb662b#diff-a631272804c78b839a9e2574b9a970a3L56) should be in `gerrit.conf.example`.

**Comment by samuelguebo** [comment]
You can go and fix the `Pylint` errors while I add the declaration you suggested in `gerrit.conf.example`.

**Pull request merged**
